services:

# Reverse Proxy Container
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
    command:
      # API and dashboard configuration
      - "--api.dashboard=true"
      # Entry points configuration
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP redirect to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Docker provider configuration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Set up the TLS configuration for our websecure listener
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=yourdomain.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.yourdomain.com"
      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    networks:
      - proxy

# Ollama Container
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    depends_on:
      - traefik
    pull_policy: always
    tty: true
    restart: always
    image: ollama/ollama:latest
    ports:
      - 11434:11434 # only required for ollama external access
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_ORIGINS=* # or OLLAMA_ORIGINS=https://bolt.yourdomain.com
      - OLLAMA_DEBUG=1
    networks:
      - proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`ollama.yourdomain.com`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.tls=true"
      - "traefik.http.routers.ollama.tls.certresolver=letsencrypt"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"

# Bolt Container
  bolt.new:
    image: your_hub_username/bolt-ai:development # feel free to use mine at aaronbolton78/bolt-ai:development
    container_name: bolt.new
    depends_on:
      - ollama
      - traefik
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - proxy
    volumes:
      - .env.local:/app/.env.local:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolt.rule=Host(`bolt.yourdomain.com`)"
      - "traefik.http.routers.bolt.entrypoints=websecure"
      - "traefik.http.routers.bolt.tls=true"
      - "traefik.http.routers.bolt.tls.certresolver=letsencrypt"
      - "traefik.http.services.bolt.loadbalancer.server.port=5173"

networks:
  proxy:
    name: proxy
    driver: bridge